name: Deploy to AWS EC2

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🚚 Copy files to AWS via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*" # <--- CHANGED: Copies the contents, not the root folder itself
          target: "/home/ubuntu/webrtc-app"

      - name: 🚀 Execute deployment on AWS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/webrtc-app
            sudo docker-compose down
            sudo docker-compose up -d --build
            sudo docker image prune -f